AllCops:
  Exclude:
    - '*.lock'
    - 'vendor/**/*'

Documentation:
  Enabled: true

Metrics/LineLength:
  Max: 200

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 60
  CountComments: false
  Enabled: true

Metrics/BlockLength:
  Max: 40

Style/Encoding:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/EmptyLiteral:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

Documentation:
  Enabled: false

CaseIndentation:
  # Valid values are: case, end
  EnforcedStyle: case
  IndentOneStep: false

Metrics/AbcSize:
  Max: 25
